config/routes.rb
Rails.application.routes.draw do

   root 'page#index'
   get '/' => 'page#index', as: "page_index"
   get '/edit' => 'page#file_edit', as: "file_edit" 
   post '/preview' => 'page#file_preview', as: "file_preview"
   post '/save' => 'page#file_save', as: "file_save"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_path, only: [:index,:file_edit]
  before_action :file_save_valid, only: [:file_save]
  def index
    @is_readable = readable || ""
    @data = refresh_data
    @current_path = params[:path] || ""
  end

  def file_edit
    @is_readable = readable || ""
  end

  def file_preview
    @body = params[:body].gsub("\r","")
    @path = params[:path]
  end

  def file_save
    file = File.new(params[:path],'w')
    file.write params[:data]
    file.close
    redirect_to page_index_path,notice:"success"
  end
private
  def file_save_valid
    #add your valid here
  end

  def refresh_data
    data = []
    files = `ls #{@path}`
    files.split("\n").each do |file|
      data << "#{file}"
    end
    data
  end

  def readable
    data = ""
    data = `cat #{@path}`
    data
  end

  def cmd(input)
  end

  def set_path
    if params[:path]
      raise if params[:path].include?("..") 
    end
    @path = Dir.pwd
    @path += params[:path] if params[:path]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
  def set_notice
    if flash[:notice]
     raw "<div class='alert'>#{notice}</div>"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webgit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/file_edit.html.erb
<%= form_tag file_preview_path %>
  <%= text_area_tag "body" , @is_readable ,style:"width:65%; height:75%; display:block;"%>
  <%= hidden_field_tag "path" , @path %>
<%= link_to 'back', page_index_path(path:params[:path] ,style:"margin-top:10px;")%>
<%= submit_tag 'preview' ,style:"margin-top:10px;"%>

app/views/page/file_preview.html.erb
  <pre style="background-color:e1e2e4; font-weight: bold;">
<%= @body %>  <!--注意編排-->
  </pre>
<%= form_tag file_save_path %>
<%= hidden_field_tag "data" , @body %>
<%= hidden_field_tag "path" , @path %>
<%= link_to 'cancel', page_index_path, style:"margin-top:10px;"%>
<%= submit_tag 'save' ,style:"margin-top:10px;"%>

app/views/page/index.html.erb
<div class="banner" >
  <%= "Current Path = #{@path}" %>
</div>
<%= set_notice %>
<div class="container">
  <% unless @current_path.empty? %>
    <%=link_to 'back', page_index_path(path: @current_path.sub(/\/[^\/]+$/,'')) , :class=>"btn" %>
    <%# binding.pry %>
    </br>
  <% end %>

  <% unless @is_readable.empty? %>
    <pre style="background-color:e1e2e4; font-weight: bold;">
<%= @is_readable %>  <!--注意編排-->
    </pre>
    <%= link_to "edit", file_edit_path(path: @current_path) , :class=>"btn"  %>
    <%#= raw @is_readable.gsub(/\n/, '<br />') %>
  <% else %>
    <% @data.each do |t|%>
      <%=link_to t, page_index_path(path: @current_path + '/'+ t ) %>
      </br>
    <% end %>
  <% end %>
</div>

<style>
  .banner{
    font-size: 25px;
    display:block;
  }
 .alert {
  background-color: #ff99ff;
  display: inline-block;
 }
 .container {
  display: inline-block;
  float:left;
  }
 .container .btn {
    font-size: 20px;
    background-color: #ffffcc;
  }
 
</style>